class Autogenerated {
  String? status;
  Message? message;
  String? token;

  Autogenerated({this.status, this.message, this.token});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'] != null ? Message.fromJson(json['message']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    if (message != null) {
      data['message'] = message!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class Message {
  String? username;
  String? email;
  String? password;
  bool? isAdmin;
  List<dynamic>? followers;
  List<dynamic>? following;
  String? sId;
  String? createdAt;
  String? updatedAt;
  int? iV;

  Message({
    this.username,
    this.email,
    this.password,
    this.isAdmin,
    this.followers,
    this.following,
    this.sId,
    this.createdAt,
    this.updatedAt,
    this.iV,
  });

  Message.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    email = json['email'];
    password = json['password'];
    isAdmin = json['isAdmin'];
    followers = json['followers'];
    following = json['following'];
    sId = json['_id'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['username'] = username;
    data['email'] = email;
    data['password'] = password;
    data['isAdmin'] = isAdmin;
    data['followers'] = followers;
    data['following'] = following;
    data['_id'] = sId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = iV;
    return data;
  }
}
